title: EuroEval
description: EuroEval - Evaluation framework for LLMs
nav:
  - title: About
    pages:
      - path: README.md
        title: Overview
  - title: Leaderboards
    pages:
      - path: leaderboards/
        title: Leaderboards
      - path: extras/radial_plotter.md
        title: Compare Models
  - title: Tasks
    pages:
      - path: tasks/
        title: Tasks
  - title: Datasets
    pages:
      - path: datasets/
        title: Datasets
  - title: Methodology
    pages:
      - path: methodology.md
        title: Methodology
  - title: FAQ
    pages:
      - path: faq.md
        title: FAQ
  - title: Python Package
    pages:
      - path: python-package.md
        title: Python Package
