name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  code-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install pre-commit
        run: pipx install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  pytest-linux:
    if: github.event.pull_request.draft == false
    strategy:
        matrix:
            python-version: ["3.10", "3.11"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install --extras cpu_all --no-interaction --no-cache

      - name: Test with pytest
        run: TEST_ALL_DATASETS=1 poetry run pytest
        env:
          HUGGINGFACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_HUB_TOKEN }}

      - name: Delete ScandEval cache
        run: rm -rf .scandeval_cache

  pytest-macos:
    if: github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'macos')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install --extras cpu_all --no-interaction --no-cache

      - name: Test with pytest
        run: TEST_ALL_DATASETS=1 poetry run pytest
        env:
          HUGGINGFACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_HUB_TOKEN }}

      - name: Delete ScandEval cache
        run: rm -rf .scandeval_cache
